[package]
name = "alphabet_match_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
ahash = "0.8"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
