[package]
name = "bench_match"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench"
harness = false

[dependencies]
ahash = "0.8.11"
arrayvec = "0.7.6"
boomphf = "0.6.0"
criterion = "0.5.1"
lazy_static = "1.5.0"
phf = { version = "0.11", features = ["macros"] }

[workspace]
