// AUTOMATICALLY GENERATED BY:
//
//   ucd-generate script ./ --chars
//
// Unicode version: 16.0.0.
//
// ucd-generate 0.3.0 is available on crates.io.
#![allow(dead_code)]
#![allow(clippy::redundant_static_lifetimes)]

use crate::alphabet::Script;

pub const BY_NAME: &'static [(Script, &'static [(char, char)])] = &[
    /* (Script::Arabic, ARABIC),
    (Script::Armenian, ARMENIAN),
    (Script::Bengali, BENGALI),
    (Script::Cyrillic, CYRILLIC),
    (Script::Devanagari, DEVANAGARI),
    (Script::Georgian, GEORGIAN),
    (Script::Greek, GREEK),
    (Script::Gujarati, GUJARATI),
    (Script::Gurmukhi, GURMUKHI),
    (Script::Han, HAN),
    (Script::Hangul, HANGUL),
    (Script::Hebrew, HEBREW),
    (Script::Hiragana, HIRAGANA),
    (Script::Katakana, KATAKANA),
    (Script::Latin, LATIN),
    (Script::Tamil, TAMIL),
    (Script::Telugu, TELUGU),
    (Script::Thai, THAI), */
    (Script::Adlam, ADLAM),
    (Script::Ahom, AHOM),
    (Script::Anatolian_Hieroglyphs, ANATOLIAN_HIEROGLYPHS),
    (Script::Arabic, ARABIC),
    (Script::Armenian, ARMENIAN),
    (Script::Avestan, AVESTAN),
    (Script::Balinese, BALINESE),
    (Script::Bamum, BAMUM),
    (Script::Bassa_Vah, BASSA_VAH),
    // (Script::Batak, BATAK),
    (Script::Bengali, BENGALI),
    (Script::Bhaiksuki, BHAIKSUKI),
    (Script::Bopomofo, BOPOMOFO),
    (Script::Brahmi, BRAHMI),
    // (Script::Braille, BRAILLE),
    (Script::Buginese, BUGINESE),
    (Script::Buhid, BUHID),
    // (Script::Canadian_Aboriginal, CANADIAN_ABORIGINAL),
    (Script::Carian, CARIAN),
    (Script::Caucasian_Albanian, CAUCASIAN_ALBANIAN),
    (Script::Chakma, CHAKMA),
    (Script::Cham, CHAM),
    (Script::Cherokee, CHEROKEE),
    (Script::Chorasmian, CHORASMIAN),
    // (Script::Common, COMMON),
    (Script::Coptic, COPTIC),
    (Script::Cuneiform, CUNEIFORM),
    (Script::Cypriot, CYPRIOT),
    // (Script::Cypro_Minoan, CYPRO_MINOAN),
    (Script::Cyrillic, CYRILLIC),
    (Script::Deseret, DESERET),
    (Script::Devanagari, DEVANAGARI),
    (Script::Dives_Akuru, DIVES_AKURU),
    (Script::Dogra, DOGRA),
    // (Script::Duployan, DUPLOYAN),
    (Script::Egyptian_Hieroglyphs, EGYPTIAN_HIEROGLYPHS),
    (Script::Elbasan, ELBASAN),
    (Script::Elymaic, ELYMAIC),
    (Script::Ethiopic, ETHIOPIC),
    (Script::Garay, GARAY),
    (Script::Georgian, GEORGIAN),
    (Script::Glagolitic, GLAGOLITIC),
    (Script::Gothic, GOTHIC),
    (Script::Grantha, GRANTHA),
    (Script::Greek, GREEK),
    (Script::Gujarati, GUJARATI),
    (Script::Gunjala_Gondi, GUNJALA_GONDI),
    (Script::Gurmukhi, GURMUKHI),
    (Script::Gurung_Khema, GURUNG_KHEMA),
    (Script::Han, HAN),
    (Script::Hangul, HANGUL),
    (Script::Hanifi_Rohingya, HANIFI_ROHINGYA),
    (Script::Hanunoo, HANUNOO),
    (Script::Hatran, HATRAN),
    (Script::Hebrew, HEBREW),
    (Script::Hiragana, HIRAGANA),
    (Script::Imperial_Aramaic, IMPERIAL_ARAMAIC),
    // (Script::Inherited, INHERITED),
    (Script::Inscriptional_Pahlavi, INSCRIPTIONAL_PAHLAVI),
    (Script::Inscriptional_Parthian, INSCRIPTIONAL_PARTHIAN),
    (Script::Javanese, JAVANESE),
    (Script::Kaithi, KAITHI),
    (Script::Kannada, KANNADA),
    (Script::Katakana, KATAKANA),
    (Script::Kawi, KAWI),
    (Script::Kayah_Li, KAYAH_LI),
    (Script::Kharoshthi, KHAROSHTHI),
    (Script::Khitan_Small_Script, KHITAN_SMALL_SCRIPT),
    (Script::Khmer, KHMER),
    (Script::Khojki, KHOJKI),
    (Script::Khudawadi, KHUDAWADI),
    (Script::Kirat_Rai, KIRAT_RAI),
    (Script::Lao, LAO),
    (Script::Latin, LATIN),
    (Script::Lepcha, LEPCHA),
    (Script::Limbu, LIMBU),
    // (Script::Linear_A, LINEAR_A),
    (Script::Linear_B, LINEAR_B),
    (Script::Lisu, LISU),
    (Script::Lycian, LYCIAN),
    (Script::Lydian, LYDIAN),
    (Script::Mahajani, MAHAJANI),
    (Script::Makasar, MAKASAR),
    (Script::Malayalam, MALAYALAM),
    (Script::Mandaic, MANDAIC),
    (Script::Manichaean, MANICHAEAN),
    (Script::Marchen, MARCHEN),
    (Script::Masaram_Gondi, MASARAM_GONDI),
    (Script::Medefaidrin, MEDEFAIDRIN),
    (Script::Meetei_Mayek, MEETEI_MAYEK),
    (Script::Mende_Kikakui, MENDE_KIKAKUI),
    (Script::Meroitic_Cursive, MEROITIC_CURSIVE),
    (Script::Meroitic_Hieroglyphs, MEROITIC_HIEROGLYPHS),
    (Script::Miao, MIAO),
    (Script::Modi, MODI),
    (Script::Mongolian, MONGOLIAN),
    (Script::Mro, MRO),
    (Script::Multani, MULTANI),
    (Script::Myanmar, MYANMAR),
    (Script::Nabataean, NABATAEAN),
    (Script::Nag_Mundari, NAG_MUNDARI),
    (Script::Nandinagari, NANDINAGARI),
    (Script::New_Tai_Lue, NEW_TAI_LUE),
    (Script::Newa, NEWA),
    (Script::Nko, NKO),
    (Script::Nushu, NUSHU),
    (Script::Nyiakeng_Puachue_Hmong, NYIAKENG_PUACHUE_HMONG),
    (Script::Ogham, OGHAM),
    (Script::Ol_Chiki, OL_CHIKI),
    (Script::Ol_Onal, OL_ONAL),
    (Script::Old_Hungarian, OLD_HUNGARIAN),
    (Script::Old_Italic, OLD_ITALIC),
    (Script::Old_North_Arabian, OLD_NORTH_ARABIAN),
    (Script::Old_Permic, OLD_PERMIC),
    (Script::Old_Persian, OLD_PERSIAN),
    (Script::Old_Sogdian, OLD_SOGDIAN),
    (Script::Old_South_Arabian, OLD_SOUTH_ARABIAN),
    (Script::Old_Turkic, OLD_TURKIC),
    (Script::Old_Uyghur, OLD_UYGHUR),
    (Script::Oriya, ORIYA),
    (Script::Osage, OSAGE),
    (Script::Osmanya, OSMANYA),
    (Script::Pahawh_Hmong, PAHAWH_HMONG),
    (Script::Palmyrene, PALMYRENE),
    (Script::Pau_Cin_Hau, PAU_CIN_HAU),
    (Script::Phags_Pa, PHAGS_PA),
    (Script::Phoenician, PHOENICIAN),
    (Script::Psalter_Pahlavi, PSALTER_PAHLAVI),
    (Script::Rejang, REJANG),
    (Script::Runic, RUNIC),
    (Script::Samaritan, SAMARITAN),
    (Script::Saurashtra, SAURASHTRA),
    (Script::Sharada, SHARADA),
    (Script::Shavian, SHAVIAN),
    (Script::Siddham, SIDDHAM),
    (Script::SignWriting, SIGNWRITING),
    (Script::Sinhala, SINHALA),
    (Script::Sogdian, SOGDIAN),
    (Script::Sora_Sompeng, SORA_SOMPENG),
    (Script::Soyombo, SOYOMBO),
    (Script::Sundanese, SUNDANESE),
    (Script::Sunuwar, SUNUWAR),
    (Script::Syloti_Nagri, SYLOTI_NAGRI),
    (Script::Syriac, SYRIAC),
    (Script::Tagalog, TAGALOG),
    (Script::Tagbanwa, TAGBANWA),
    (Script::Tai_Le, TAI_LE),
    (Script::Tai_Tham, TAI_THAM),
    (Script::Tai_Viet, TAI_VIET),
    (Script::Takri, TAKRI),
    (Script::Tamil, TAMIL),
    (Script::Tangsa, TANGSA),
    (Script::Tangut, TANGUT),
    (Script::Telugu, TELUGU),
    (Script::Thaana, THAANA),
    (Script::Thai, THAI),
    (Script::Tibetan, TIBETAN),
    (Script::Tifinagh, TIFINAGH),
    (Script::Tirhuta, TIRHUTA),
    (Script::Todhri, TODHRI),
    (Script::Toto, TOTO),
    (Script::Tulu_Tigalari, TULU_TIGALARI),
    (Script::Ugaritic, UGARITIC),
    (Script::Vai, VAI),
    (Script::Vithkuqi, VITHKUQI),
    (Script::Wancho, WANCHO),
    (Script::Warang_Citi, WARANG_CITI),
    (Script::Yezidi, YEZIDI),
    (Script::Yi, YI),
    (Script::Zanabazar_Square, ZANABAZAR_SQUARE),
];

pub const ADLAM: &'static [(char, char)] = &[('𞤀', '𞥋'), ('𞥐', '𞥙'), ('𞥞', '𞥟')];

pub const AHOM: &'static [(char, char)] = &[('𑜀', '𑜚'), ('\u{1171d}', '\u{1172b}'), ('𑜰', '𑝆')];

pub const ANATOLIAN_HIEROGLYPHS: &'static [(char, char)] = &[('𔐀', '𔙆')];

pub const ARABIC: &'static [(char, char)] = &[
    ('\u{600}', '\u{604}'),
    ('؆', '؋'),
    ('؍', '\u{61a}'),
    ('\u{61c}', '؞'),
    ('ؠ', 'ؿ'),
    ('ف', 'ي'),
    ('\u{656}', 'ٯ'),
    ('ٱ', '\u{6dc}'),
    ('۞', 'ۿ'),
    ('ݐ', 'ݿ'),
    ('ࡰ', 'ࢎ'),
    ('\u{890}', '\u{891}'),
    ('\u{897}', '\u{8e1}'),
    ('\u{8e3}', '\u{8ff}'),
    ('ﭐ', '﯂'),
    ('ﯓ', 'ﴽ'),
    ('﵀', 'ﶏ'),
    ('ﶒ', 'ﷇ'),
    ('﷏', '﷏'),
    ('ﷰ', '﷿'),
    ('ﹰ', 'ﹴ'),
    ('ﹶ', 'ﻼ'),
    ('𐹠', '𐹾'),
    ('\u{10ec2}', '\u{10ec4}'),
    ('\u{10efc}', '\u{10eff}'),
    ('𞸀', '𞸃'),
    ('𞸅', '𞸟'),
    ('𞸡', '𞸢'),
    ('𞸤', '𞸤'),
    ('𞸧', '𞸧'),
    ('𞸩', '𞸲'),
    ('𞸴', '𞸷'),
    ('𞸹', '𞸹'),
    ('𞸻', '𞸻'),
    ('𞹂', '𞹂'),
    ('𞹇', '𞹇'),
    ('𞹉', '𞹉'),
    ('𞹋', '𞹋'),
    ('𞹍', '𞹏'),
    ('𞹑', '𞹒'),
    ('𞹔', '𞹔'),
    ('𞹗', '𞹗'),
    ('𞹙', '𞹙'),
    ('𞹛', '𞹛'),
    ('𞹝', '𞹝'),
    ('𞹟', '𞹟'),
    ('𞹡', '𞹢'),
    ('𞹤', '𞹤'),
    ('𞹧', '𞹪'),
    ('𞹬', '𞹲'),
    ('𞹴', '𞹷'),
    ('𞹹', '𞹼'),
    ('𞹾', '𞹾'),
    ('𞺀', '𞺉'),
    ('𞺋', '𞺛'),
    ('𞺡', '𞺣'),
    ('𞺥', '𞺩'),
    ('𞺫', '𞺻'),
    ('𞻰', '𞻱'),
];

pub const ARMENIAN: &'static [(char, char)] = &[('Ա', 'Ֆ'), ('ՙ', '֊'), ('֍', '֏'), ('ﬓ', 'ﬗ')];

pub const AVESTAN: &'static [(char, char)] = &[('𐬀', '𐬵'), ('𐬹', '𐬿')];

pub const BALINESE: &'static [(char, char)] = &[('\u{1b00}', 'ᭌ'), ('\u{1b4e}', '\u{1b7f}')];

pub const BAMUM: &'static [(char, char)] = &[('ꚠ', '꛷'), ('𖠀', '𖨸')];

pub const BASSA_VAH: &'static [(char, char)] = &[('𖫐', '𖫭'), ('\u{16af0}', '𖫵')];

pub const BATAK: &'static [(char, char)] = &[('ᯀ', '᯳'), ('᯼', '᯿')];

pub const BENGALI: &'static [(char, char)] = &[
    ('ঀ', 'ঃ'),
    ('অ', 'ঌ'),
    ('এ', 'ঐ'),
    ('ও', 'ন'),
    ('প', 'র'),
    ('ল', 'ল'),
    ('শ', 'হ'),
    ('\u{9bc}', '\u{9c4}'),
    ('ে', 'ৈ'),
    ('ো', 'ৎ'),
    ('\u{9d7}', '\u{9d7}'),
    ('ড়', 'ঢ়'),
    ('য়', '\u{9e3}'),
    ('০', '\u{9fe}'),
];

pub const BHAIKSUKI: &'static [(char, char)] = &[
    ('𑰀', '𑰈'),
    ('𑰊', '\u{11c36}'),
    ('\u{11c38}', '𑱅'),
    ('𑱐', '𑱬'),
];

pub const BOPOMOFO: &'static [(char, char)] = &[('˪', '˫'), ('ㄅ', 'ㄯ'), ('ㆠ', 'ㆿ')];

pub const BRAHMI: &'static [(char, char)] = &[('𑀀', '𑁍'), ('𑁒', '𑁵'), ('\u{1107f}', '\u{1107f}')];

pub const BRAILLE: &'static [(char, char)] = &[('⠀', '⣿')];

pub const BUGINESE: &'static [(char, char)] = &[('ᨀ', '\u{1a1b}'), ('᨞', '᨟')];

pub const BUHID: &'static [(char, char)] = &[('ᝀ', '\u{1753}')];

pub const CANADIAN_ABORIGINAL: &'static [(char, char)] = &[('᐀', 'ᙿ'), ('ᢰ', 'ᣵ'), ('𑪰', '𑪿')];

pub const CARIAN: &'static [(char, char)] = &[('𐊠', '𐋐')];

pub const CAUCASIAN_ALBANIAN: &'static [(char, char)] = &[('𐔰', '𐕣'), ('𐕯', '𐕯')];

pub const CHAKMA: &'static [(char, char)] = &[('\u{11100}', '\u{11134}'), ('𑄶', '𑅇')];

pub const CHAM: &'static [(char, char)] = &[('ꨀ', '\u{aa36}'), ('ꩀ', 'ꩍ'), ('꩐', '꩙'), ('꩜', '꩟')];

pub const CHEROKEE: &'static [(char, char)] = &[('Ꭰ', 'Ᏽ'), ('ᏸ', 'ᏽ'), ('ꭰ', 'ꮿ')];

pub const CHORASMIAN: &'static [(char, char)] = &[('𐾰', '𐿋')];

pub const COMMON: &'static [(char, char)] = &[
    ('\0', '@'),
    ('[', '`'),
    ('{', '©'),
    ('«', '¹'),
    ('»', '¿'),
    ('×', '×'),
    ('÷', '÷'),
    ('ʹ', '˟'),
    ('˥', '˩'),
    ('ˬ', '˿'),
    ('ʹ', 'ʹ'),
    (';', ';'),
    ('΅', '΅'),
    ('·', '·'),
    ('\u{605}', '\u{605}'),
    ('،', '،'),
    ('؛', '؛'),
    ('؟', '؟'),
    ('ـ', 'ـ'),
    ('\u{6dd}', '\u{6dd}'),
    ('\u{8e2}', '\u{8e2}'),
    ('।', '॥'),
    ('฿', '฿'),
    ('࿕', '࿘'),
    ('჻', '჻'),
    ('᛫', '᛭'),
    ('᜵', '᜶'),
    ('᠂', '᠃'),
    ('᠅', '᠅'),
    ('᳓', '᳓'),
    ('᳡', '᳡'),
    ('ᳩ', 'ᳬ'),
    ('ᳮ', 'ᳳ'),
    ('ᳵ', '᳷'),
    ('ᳺ', 'ᳺ'),
    ('\u{2000}', '\u{200b}'),
    ('\u{200e}', '\u{2064}'),
    ('\u{2066}', '⁰'),
    ('⁴', '⁾'),
    ('₀', '₎'),
    ('₠', '⃀'),
    ('℀', '℥'),
    ('℧', '℩'),
    ('ℬ', 'ℱ'),
    ('ℳ', '⅍'),
    ('⅏', '⅟'),
    ('↉', '↋'),
    ('←', '\u{2429}'),
    ('⑀', '⑊'),
    ('①', '⟿'),
    ('⤀', '⭳'),
    ('⭶', '⮕'),
    ('⮗', '⯿'),
    ('⸀', '⹝'),
    ('⿰', '〄'),
    ('〆', '〆'),
    ('〈', '〠'),
    ('〰', '〷'),
    ('〼', '〿'),
    ('゛', '゜'),
    ('゠', '゠'),
    ('・', 'ー'),
    ('㆐', '㆟'),
    ('㇀', '\u{31e5}'),
    ('㇯', '㇯'),
    ('㈠', '㉟'),
    ('㉿', '㋏'),
    ('㋿', '㋿'),
    ('㍘', '㏿'),
    ('䷀', '䷿'),
    ('꜀', '꜡'),
    ('ꞈ', '꞊'),
    ('꠰', '꠹'),
    ('꤮', '꤮'),
    ('ꧏ', 'ꧏ'),
    ('꭛', '꭛'),
    ('꭪', '꭫'),
    ('﴾', '﴿'),
    ('︐', '︙'),
    ('︰', '﹒'),
    ('﹔', '﹦'),
    ('﹨', '﹫'),
    ('\u{feff}', '\u{feff}'),
    ('！', '＠'),
    ('［', '｀'),
    ('｛', '･'),
    ('ｰ', 'ｰ'),
    ('\u{ff9e}', '\u{ff9f}'),
    ('￠', '￦'),
    ('￨', '￮'),
    ('\u{fff9}', '�'),
    ('𐄀', '𐄂'),
    ('𐄇', '𐄳'),
    ('𐄷', '𐄿'),
    ('𐆐', '𐆜'),
    ('𐇐', '𐇼'),
    ('𐋡', '𐋻'),
    ('\u{1bca0}', '\u{1bca3}'),
    ('\u{1cc00}', '\u{1ccf9}'),
    ('\u{1cd00}', '\u{1ceb3}'),
    ('𜽐', '𜿃'),
    ('𝀀', '𝃵'),
    ('𝄀', '𝄦'),
    ('𝄩', '𝅦'),
    ('𝅪', '\u{1d17a}'),
    ('𝆃', '𝆄'),
    ('𝆌', '𝆩'),
    ('𝆮', '𝇪'),
    ('𝋀', '𝋓'),
    ('𝋠', '𝋳'),
    ('𝌀', '𝍖'),
    ('𝍠', '𝍸'),
    ('𝐀', '𝑔'),
    ('𝑖', '𝒜'),
    ('𝒞', '𝒟'),
    ('𝒢', '𝒢'),
    ('𝒥', '𝒦'),
    ('𝒩', '𝒬'),
    ('𝒮', '𝒹'),
    ('𝒻', '𝒻'),
    ('𝒽', '𝓃'),
    ('𝓅', '𝔅'),
    ('𝔇', '𝔊'),
    ('𝔍', '𝔔'),
    ('𝔖', '𝔜'),
    ('𝔞', '𝔹'),
    ('𝔻', '𝔾'),
    ('𝕀', '𝕄'),
    ('𝕆', '𝕆'),
    ('𝕊', '𝕐'),
    ('𝕒', '𝚥'),
    ('𝚨', '𝟋'),
    ('𝟎', '𝟿'),
    ('𞱱', '𞲴'),
    ('𞴁', '𞴽'),
    ('🀀', '🀫'),
    ('🀰', '🂓'),
    ('🂠', '🂮'),
    ('🂱', '🂿'),
    ('🃁', '🃏'),
    ('🃑', '🃵'),
    ('🄀', '🆭'),
    ('🇦', '🇿'),
    ('🈁', '🈂'),
    ('🈐', '🈻'),
    ('🉀', '🉈'),
    ('🉐', '🉑'),
    ('🉠', '🉥'),
    ('🌀', '🛗'),
    ('🛜', '🛬'),
    ('🛰', '🛼'),
    ('🜀', '🝶'),
    ('🝻', '🟙'),
    ('🟠', '🟫'),
    ('🟰', '🟰'),
    ('🠀', '🠋'),
    ('🠐', '🡇'),
    ('🡐', '🡙'),
    ('🡠', '🢇'),
    ('🢐', '🢭'),
    ('🢰', '\u{1f8bb}'),
    ('\u{1f8c0}', '\u{1f8c1}'),
    ('🤀', '🩓'),
    ('🩠', '🩭'),
    ('🩰', '🩼'),
    ('🪀', '\u{1fa89}'),
    ('\u{1fa8f}', '\u{1fac6}'),
    ('🫎', '\u{1fadc}'),
    ('\u{1fadf}', '\u{1fae9}'),
    ('🫰', '🫸'),
    ('🬀', '🮒'),
    ('🮔', '🯹'),
    ('\u{e0001}', '\u{e0001}'),
    ('\u{e0020}', '\u{e007f}'),
];

pub const COPTIC: &'static [(char, char)] = &[('Ϣ', 'ϯ'), ('Ⲁ', 'ⳳ'), ('⳹', '⳿')];

pub const CUNEIFORM: &'static [(char, char)] = &[('𒀀', '𒎙'), ('𒐀', '𒑮'), ('𒑰', '𒑴'), ('𒒀', '𒕃')];

pub const CYPRIOT: &'static [(char, char)] = &[
    ('𐠀', '𐠅'),
    ('𐠈', '𐠈'),
    ('𐠊', '𐠵'),
    ('𐠷', '𐠸'),
    ('𐠼', '𐠼'),
    ('𐠿', '𐠿'),
];

pub const CYPRO_MINOAN: &'static [(char, char)] = &[('𒾐', '𒿲')];

pub const CYRILLIC: &'static [(char, char)] = &[
    ('Ѐ', '\u{484}'),
    ('\u{487}', 'ԯ'),
    ('ᲀ', '\u{1c8a}'),
    ('ᴫ', 'ᴫ'),
    ('ᵸ', 'ᵸ'),
    ('\u{2de0}', '\u{2dff}'),
    ('Ꙁ', '\u{a69f}'),
    ('\u{fe2e}', '\u{fe2f}'),
    ('𞀰', '𞁭'),
    ('\u{1e08f}', '\u{1e08f}'),
];

pub const DESERET: &'static [(char, char)] = &[('𐐀', '𐑏')];

pub const DEVANAGARI: &'static [(char, char)] = &[
    ('\u{900}', 'ॐ'),
    ('\u{955}', '\u{963}'),
    ('०', 'ॿ'),
    ('\u{a8e0}', '\u{a8ff}'),
    ('𑬀', '𑬉'),
];

pub const DIVES_AKURU: &'static [(char, char)] = &[
    ('𑤀', '𑤆'),
    ('𑤉', '𑤉'),
    ('𑤌', '𑤓'),
    ('𑤕', '𑤖'),
    ('𑤘', '𑤵'),
    ('𑤷', '𑤸'),
    ('\u{1193b}', '𑥆'),
    ('𑥐', '𑥙'),
];

pub const DOGRA: &'static [(char, char)] = &[('𑠀', '𑠻')];

pub const DUPLOYAN: &'static [(char, char)] =
    &[('𛰀', '𛱪'), ('𛱰', '𛱼'), ('𛲀', '𛲈'), ('𛲐', '𛲙'), ('𛲜', '𛲟')];

pub const EGYPTIAN_HIEROGLYPHS: &'static [(char, char)] =
    &[('𓀀', '\u{13455}'), ('\u{13460}', '\u{143fa}')];

pub const ELBASAN: &'static [(char, char)] = &[('𐔀', '𐔧')];

pub const ELYMAIC: &'static [(char, char)] = &[('𐿠', '𐿶')];

pub const ETHIOPIC: &'static [(char, char)] = &[
    ('ሀ', 'ቈ'),
    ('ቊ', 'ቍ'),
    ('ቐ', 'ቖ'),
    ('ቘ', 'ቘ'),
    ('ቚ', 'ቝ'),
    ('በ', 'ኈ'),
    ('ኊ', 'ኍ'),
    ('ነ', 'ኰ'),
    ('ኲ', 'ኵ'),
    ('ኸ', 'ኾ'),
    ('ዀ', 'ዀ'),
    ('ዂ', 'ዅ'),
    ('ወ', 'ዖ'),
    ('ዘ', 'ጐ'),
    ('ጒ', 'ጕ'),
    ('ጘ', 'ፚ'),
    ('\u{135d}', '፼'),
    ('ᎀ', '᎙'),
    ('ⶀ', 'ⶖ'),
    ('ⶠ', 'ⶦ'),
    ('ⶨ', 'ⶮ'),
    ('ⶰ', 'ⶶ'),
    ('ⶸ', 'ⶾ'),
    ('ⷀ', 'ⷆ'),
    ('ⷈ', 'ⷎ'),
    ('ⷐ', 'ⷖ'),
    ('ⷘ', 'ⷞ'),
    ('ꬁ', 'ꬆ'),
    ('ꬉ', 'ꬎ'),
    ('ꬑ', 'ꬖ'),
    ('ꬠ', 'ꬦ'),
    ('ꬨ', 'ꬮ'),
    ('𞟠', '𞟦'),
    ('𞟨', '𞟫'),
    ('𞟭', '𞟮'),
    ('𞟰', '𞟾'),
];

pub const GARAY: &'static [(char, char)] = &[
    ('\u{10d40}', '\u{10d65}'),
    ('\u{10d69}', '\u{10d85}'),
    ('\u{10d8e}', '\u{10d8f}'),
];

pub const GEORGIAN: &'static [(char, char)] = &[
    ('Ⴀ', 'Ⴥ'),
    ('Ⴧ', 'Ⴧ'),
    ('Ⴭ', 'Ⴭ'),
    ('ა', 'ჺ'),
    ('ჼ', 'ჿ'),
    ('Ა', 'Ჺ'),
    ('Ჽ', 'Ჿ'),
    ('ⴀ', 'ⴥ'),
    ('ⴧ', 'ⴧ'),
    ('ⴭ', 'ⴭ'),
];

pub const GLAGOLITIC: &'static [(char, char)] = &[
    ('Ⰰ', 'ⱟ'),
    ('\u{1e000}', '\u{1e006}'),
    ('\u{1e008}', '\u{1e018}'),
    ('\u{1e01b}', '\u{1e021}'),
    ('\u{1e023}', '\u{1e024}'),
    ('\u{1e026}', '\u{1e02a}'),
];

pub const GOTHIC: &'static [(char, char)] = &[('𐌰', '𐍊')];

pub const GRANTHA: &'static [(char, char)] = &[
    ('\u{11300}', '𑌃'),
    ('𑌅', '𑌌'),
    ('𑌏', '𑌐'),
    ('𑌓', '𑌨'),
    ('𑌪', '𑌰'),
    ('𑌲', '𑌳'),
    ('𑌵', '𑌹'),
    ('\u{1133c}', '𑍄'),
    ('𑍇', '𑍈'),
    ('𑍋', '𑍍'),
    ('𑍐', '𑍐'),
    ('\u{11357}', '\u{11357}'),
    ('𑍝', '𑍣'),
    ('\u{11366}', '\u{1136c}'),
    ('\u{11370}', '\u{11374}'),
];

pub const GREEK: &'static [(char, char)] = &[
    ('Ͱ', 'ͳ'),
    ('͵', 'ͷ'),
    ('ͺ', 'ͽ'),
    ('Ϳ', 'Ϳ'),
    ('΄', '΄'),
    ('Ά', 'Ά'),
    ('Έ', 'Ί'),
    ('Ό', 'Ό'),
    ('Ύ', 'Ρ'),
    ('Σ', 'ϡ'),
    ('ϰ', 'Ͽ'),
    ('ᴦ', 'ᴪ'),
    ('ᵝ', 'ᵡ'),
    ('ᵦ', 'ᵪ'),
    ('ᶿ', 'ᶿ'),
    ('ἀ', 'ἕ'),
    ('Ἐ', 'Ἕ'),
    ('ἠ', 'ὅ'),
    ('Ὀ', 'Ὅ'),
    ('ὐ', 'ὗ'),
    ('Ὑ', 'Ὑ'),
    ('Ὓ', 'Ὓ'),
    ('Ὕ', 'Ὕ'),
    ('Ὗ', 'ώ'),
    ('ᾀ', 'ᾴ'),
    ('ᾶ', 'ῄ'),
    ('ῆ', 'ΐ'),
    ('ῖ', 'Ί'),
    ('῝', '`'),
    ('ῲ', 'ῴ'),
    ('ῶ', '῾'),
    ('Ω', 'Ω'),
    ('ꭥ', 'ꭥ'),
    ('𐅀', '𐆎'),
    ('𐆠', '𐆠'),
    ('𝈀', '𝉅'),
];

pub const GUJARATI: &'static [(char, char)] = &[
    ('\u{a81}', 'ઃ'),
    ('અ', 'ઍ'),
    ('એ', 'ઑ'),
    ('ઓ', 'ન'),
    ('પ', 'ર'),
    ('લ', 'ળ'),
    ('વ', 'હ'),
    ('\u{abc}', '\u{ac5}'),
    ('\u{ac7}', 'ૉ'),
    ('ો', '\u{acd}'),
    ('ૐ', 'ૐ'),
    ('ૠ', '\u{ae3}'),
    ('૦', '૱'),
    ('ૹ', '\u{aff}'),
];

pub const GUNJALA_GONDI: &'static [(char, char)] = &[
    ('𑵠', '𑵥'),
    ('𑵧', '𑵨'),
    ('𑵪', '𑶎'),
    ('\u{11d90}', '\u{11d91}'),
    ('𑶓', '𑶘'),
    ('𑶠', '𑶩'),
];

pub const GURMUKHI: &'static [(char, char)] = &[
    ('\u{a01}', 'ਃ'),
    ('ਅ', 'ਊ'),
    ('ਏ', 'ਐ'),
    ('ਓ', 'ਨ'),
    ('ਪ', 'ਰ'),
    ('ਲ', 'ਲ਼'),
    ('ਵ', 'ਸ਼'),
    ('ਸ', 'ਹ'),
    ('\u{a3c}', '\u{a3c}'),
    ('ਾ', '\u{a42}'),
    ('\u{a47}', '\u{a48}'),
    ('\u{a4b}', '\u{a4d}'),
    ('\u{a51}', '\u{a51}'),
    ('ਖ਼', 'ੜ'),
    ('ਫ਼', 'ਫ਼'),
    ('੦', '੶'),
];

pub const GURUNG_KHEMA: &'static [(char, char)] = &[('\u{16100}', '\u{16139}')];

pub const HAN: &'static [(char, char)] = &[
    ('⺀', '⺙'),
    ('⺛', '⻳'),
    ('⼀', '⿕'),
    ('々', '々'),
    ('〇', '〇'),
    ('〡', '〩'),
    ('〸', '〻'),
    ('㐀', '䶿'),
    ('一', '鿿'),
    ('豈', '舘'),
    ('並', '龎'),
    ('𖿢', '𖿣'),
    ('𖿰', '𖿱'),
    ('𠀀', '𪛟'),
    ('𪜀', '𫜹'),
    ('𫝀', '𫠝'),
    ('𫠠', '𬺡'),
    ('𬺰', '𮯠'),
    ('𮯰', '𮹝'),
    ('丽', '𪘀'),
    ('𰀀', '𱍊'),
    ('𱍐', '𲎯'),
];

pub const HANGUL: &'static [(char, char)] = &[
    ('ᄀ', 'ᇿ'),
    ('\u{302e}', '\u{302f}'),
    ('ㄱ', 'ㆎ'),
    ('㈀', '㈞'),
    ('㉠', '㉾'),
    ('ꥠ', 'ꥼ'),
    ('가', '힣'),
    ('ힰ', 'ퟆ'),
    ('ퟋ', 'ퟻ'),
    ('ﾠ', 'ﾾ'),
    ('ￂ', 'ￇ'),
    ('ￊ', 'ￏ'),
    ('ￒ', 'ￗ'),
    ('ￚ', 'ￜ'),
];

pub const HANIFI_ROHINGYA: &'static [(char, char)] = &[('𐴀', '\u{10d27}'), ('𐴰', '𐴹')];

pub const HANUNOO: &'static [(char, char)] = &[('ᜠ', '᜴')];

pub const HATRAN: &'static [(char, char)] = &[('𐣠', '𐣲'), ('𐣴', '𐣵'), ('𐣻', '𐣿')];

pub const HEBREW: &'static [(char, char)] = &[
    ('\u{591}', '\u{5c7}'),
    ('א', 'ת'),
    ('ׯ', '״'),
    ('יִ', 'זּ'),
    ('טּ', 'לּ'),
    ('מּ', 'מּ'),
    ('נּ', 'סּ'),
    ('ףּ', 'פּ'),
    ('צּ', 'ﭏ'),
];

pub const HIRAGANA: &'static [(char, char)] = &[
    ('ぁ', 'ゖ'),
    ('ゝ', 'ゟ'),
    ('𛀁', '𛄟'),
    ('𛄲', '𛄲'),
    ('𛅐', '𛅒'),
    ('🈀', '🈀'),
];

pub const IMPERIAL_ARAMAIC: &'static [(char, char)] = &[('𐡀', '𐡕'), ('𐡗', '𐡟')];

pub const INHERITED: &'static [(char, char)] = &[
    ('\u{300}', '\u{36f}'),
    ('\u{485}', '\u{486}'),
    ('\u{64b}', '\u{655}'),
    ('\u{670}', '\u{670}'),
    ('\u{951}', '\u{954}'),
    ('\u{1ab0}', '\u{1ace}'),
    ('\u{1cd0}', '\u{1cd2}'),
    ('\u{1cd4}', '\u{1ce0}'),
    ('\u{1ce2}', '\u{1ce8}'),
    ('\u{1ced}', '\u{1ced}'),
    ('\u{1cf4}', '\u{1cf4}'),
    ('\u{1cf8}', '\u{1cf9}'),
    ('\u{1dc0}', '\u{1dff}'),
    ('\u{200c}', '\u{200d}'),
    ('\u{20d0}', '\u{20f0}'),
    ('\u{302a}', '\u{302d}'),
    ('\u{3099}', '\u{309a}'),
    ('\u{fe00}', '\u{fe0f}'),
    ('\u{fe20}', '\u{fe2d}'),
    ('\u{101fd}', '\u{101fd}'),
    ('\u{102e0}', '\u{102e0}'),
    ('\u{1133b}', '\u{1133b}'),
    ('\u{1cf00}', '\u{1cf2d}'),
    ('\u{1cf30}', '\u{1cf46}'),
    ('\u{1d167}', '\u{1d169}'),
    ('\u{1d17b}', '\u{1d182}'),
    ('\u{1d185}', '\u{1d18b}'),
    ('\u{1d1aa}', '\u{1d1ad}'),
    ('\u{e0100}', '\u{e01ef}'),
];

pub const INSCRIPTIONAL_PAHLAVI: &'static [(char, char)] = &[('𐭠', '𐭲'), ('𐭸', '𐭿')];

pub const INSCRIPTIONAL_PARTHIAN: &'static [(char, char)] = &[('𐭀', '𐭕'), ('𐭘', '𐭟')];

pub const JAVANESE: &'static [(char, char)] = &[('\u{a980}', '꧍'), ('꧐', '꧙'), ('꧞', '꧟')];

pub const KAITHI: &'static [(char, char)] =
    &[('\u{11080}', '\u{110c2}'), ('\u{110cd}', '\u{110cd}')];

pub const KANNADA: &'static [(char, char)] = &[
    ('ಀ', 'ಌ'),
    ('ಎ', 'ಐ'),
    ('ಒ', 'ನ'),
    ('ಪ', 'ಳ'),
    ('ವ', 'ಹ'),
    ('\u{cbc}', 'ೄ'),
    ('\u{cc6}', 'ೈ'),
    ('ೊ', '\u{ccd}'),
    ('\u{cd5}', '\u{cd6}'),
    ('ೝ', 'ೞ'),
    ('ೠ', '\u{ce3}'),
    ('೦', '೯'),
    ('ೱ', 'ೳ'),
];

pub const KATAKANA: &'static [(char, char)] = &[
    ('ァ', 'ヺ'),
    ('ヽ', 'ヿ'),
    ('ㇰ', 'ㇿ'),
    ('㋐', '㋾'),
    ('㌀', '㍗'),
    ('ｦ', 'ｯ'),
    ('ｱ', 'ﾝ'),
    ('𚿰', '𚿳'),
    ('𚿵', '𚿻'),
    ('𚿽', '𚿾'),
    ('𛀀', '𛀀'),
    ('𛄠', '𛄢'),
    ('𛅕', '𛅕'),
    ('𛅤', '𛅧'),
];

pub const KAWI: &'static [(char, char)] =
    &[('\u{11f00}', '𑼐'), ('𑼒', '\u{11f3a}'), ('𑼾', '\u{11f5a}')];

pub const KAYAH_LI: &'static [(char, char)] = &[('꤀', '\u{a92d}'), ('꤯', '꤯')];

pub const KHAROSHTHI: &'static [(char, char)] = &[
    ('𐨀', '\u{10a03}'),
    ('\u{10a05}', '\u{10a06}'),
    ('\u{10a0c}', '𐨓'),
    ('𐨕', '𐨗'),
    ('𐨙', '𐨵'),
    ('\u{10a38}', '\u{10a3a}'),
    ('\u{10a3f}', '𐩈'),
    ('𐩐', '𐩘'),
];

pub const KHITAN_SMALL_SCRIPT: &'static [(char, char)] = &[
    ('\u{16fe4}', '\u{16fe4}'),
    ('𘬀', '𘳕'),
    ('\u{18cff}', '\u{18cff}'),
];

pub const KHMER: &'static [(char, char)] = &[('ក', '\u{17dd}'), ('០', '៩'), ('៰', '៹'), ('᧠', '᧿')];

pub const KHOJKI: &'static [(char, char)] = &[('𑈀', '𑈑'), ('𑈓', '\u{11241}')];

pub const KHUDAWADI: &'static [(char, char)] = &[('𑊰', '\u{112ea}'), ('𑋰', '𑋹')];

pub const KIRAT_RAI: &'static [(char, char)] = &[('\u{16d40}', '\u{16d79}')];

pub const LAO: &'static [(char, char)] = &[
    ('ກ', 'ຂ'),
    ('ຄ', 'ຄ'),
    ('ຆ', 'ຊ'),
    ('ຌ', 'ຣ'),
    ('ລ', 'ລ'),
    ('ວ', 'ຽ'),
    ('ເ', 'ໄ'),
    ('ໆ', 'ໆ'),
    ('\u{ec8}', '\u{ece}'),
    ('໐', '໙'),
    ('ໜ', 'ໟ'),
];

pub const LATIN: &'static [(char, char)] = &[
    ('A', 'Z'),
    ('a', 'z'),
    ('ª', 'ª'),
    ('º', 'º'),
    ('À', 'Ö'),
    ('Ø', 'ö'),
    ('ø', 'ʸ'),
    ('ˠ', 'ˤ'),
    ('ᴀ', 'ᴥ'),
    ('ᴬ', 'ᵜ'),
    ('ᵢ', 'ᵥ'),
    ('ᵫ', 'ᵷ'),
    ('ᵹ', 'ᶾ'),
    ('Ḁ', 'ỿ'),
    ('ⁱ', 'ⁱ'),
    ('ⁿ', 'ⁿ'),
    ('ₐ', 'ₜ'),
    ('K', 'Å'),
    ('Ⅎ', 'Ⅎ'),
    ('ⅎ', 'ⅎ'),
    ('Ⅰ', 'ↈ'),
    ('Ⱡ', 'Ɀ'),
    ('Ꜣ', 'ꞇ'),
    ('Ꞌ', '\u{a7cd}'),
    ('Ꟑ', 'ꟑ'),
    ('ꟓ', 'ꟓ'),
    ('ꟕ', '\u{a7dc}'),
    ('ꟲ', 'ꟿ'),
    ('ꬰ', 'ꭚ'),
    ('ꭜ', 'ꭤ'),
    ('ꭦ', 'ꭩ'),
    ('ﬀ', 'ﬆ'),
    ('Ａ', 'Ｚ'),
    ('ａ', 'ｚ'),
    ('𐞀', '𐞅'),
    ('𐞇', '𐞰'),
    ('𐞲', '𐞺'),
    ('𝼀', '𝼞'),
    ('𝼥', '𝼪'),
];

pub const LEPCHA: &'static [(char, char)] = &[('ᰀ', '\u{1c37}'), ('᰻', '᱉'), ('ᱍ', 'ᱏ')];

pub const LIMBU: &'static [(char, char)] = &[
    ('ᤀ', 'ᤞ'),
    ('\u{1920}', 'ᤫ'),
    ('ᤰ', '\u{193b}'),
    ('᥀', '᥀'),
    ('᥄', '᥏'),
];

pub const LINEAR_A: &'static [(char, char)] = &[('𐘀', '𐜶'), ('𐝀', '𐝕'), ('𐝠', '𐝧')];

pub const LINEAR_B: &'static [(char, char)] = &[
    ('𐀀', '𐀋'),
    ('𐀍', '𐀦'),
    ('𐀨', '𐀺'),
    ('𐀼', '𐀽'),
    ('𐀿', '𐁍'),
    ('𐁐', '𐁝'),
    ('𐂀', '𐃺'),
];

pub const LISU: &'static [(char, char)] = &[('ꓐ', '꓿'), ('𑾰', '𑾰')];

pub const LYCIAN: &'static [(char, char)] = &[('𐊀', '𐊜')];

pub const LYDIAN: &'static [(char, char)] = &[('𐤠', '𐤹'), ('𐤿', '𐤿')];

pub const MAHAJANI: &'static [(char, char)] = &[('𑅐', '𑅶')];

pub const MAKASAR: &'static [(char, char)] = &[('𑻠', '𑻸')];

pub const MALAYALAM: &'static [(char, char)] = &[
    ('\u{d00}', 'ഌ'),
    ('എ', 'ഐ'),
    ('ഒ', '\u{d44}'),
    ('െ', 'ൈ'),
    ('ൊ', '൏'),
    ('ൔ', '\u{d63}'),
    ('൦', 'ൿ'),
];

pub const MANDAIC: &'static [(char, char)] = &[('ࡀ', '\u{85b}'), ('࡞', '࡞')];

pub const MANICHAEAN: &'static [(char, char)] = &[('𐫀', '\u{10ae6}'), ('𐫫', '𐫶')];

pub const MARCHEN: &'static [(char, char)] =
    &[('𑱰', '𑲏'), ('\u{11c92}', '\u{11ca7}'), ('𑲩', '\u{11cb6}')];

pub const MASARAM_GONDI: &'static [(char, char)] = &[
    ('𑴀', '𑴆'),
    ('𑴈', '𑴉'),
    ('𑴋', '\u{11d36}'),
    ('\u{11d3a}', '\u{11d3a}'),
    ('\u{11d3c}', '\u{11d3d}'),
    ('\u{11d3f}', '\u{11d47}'),
    ('𑵐', '𑵙'),
];

pub const MEDEFAIDRIN: &'static [(char, char)] = &[('𖹀', '𖺚')];

pub const MEETEI_MAYEK: &'static [(char, char)] =
    &[('ꫠ', '\u{aaf6}'), ('ꯀ', '\u{abed}'), ('꯰', '꯹')];

pub const MENDE_KIKAKUI: &'static [(char, char)] = &[('𞠀', '𞣄'), ('𞣇', '\u{1e8d6}')];

pub const MEROITIC_CURSIVE: &'static [(char, char)] = &[('𐦠', '𐦷'), ('𐦼', '𐧏'), ('𐧒', '𐧿')];

pub const MEROITIC_HIEROGLYPHS: &'static [(char, char)] = &[('𐦀', '𐦟')];

pub const MIAO: &'static [(char, char)] = &[('𖼀', '𖽊'), ('\u{16f4f}', '𖾇'), ('\u{16f8f}', '𖾟')];

pub const MODI: &'static [(char, char)] = &[('𑘀', '𑙄'), ('𑙐', '𑙙')];

pub const MONGOLIAN: &'static [(char, char)] = &[
    ('᠀', '᠁'),
    ('᠄', '᠄'),
    ('᠆', '᠙'),
    ('ᠠ', 'ᡸ'),
    ('ᢀ', 'ᢪ'),
    ('𑙠', '𑙬'),
];

pub const MRO: &'static [(char, char)] = &[('𖩀', '𖩞'), ('𖩠', '𖩩'), ('𖩮', '𖩯')];

pub const MULTANI: &'static [(char, char)] =
    &[('𑊀', '𑊆'), ('𑊈', '𑊈'), ('𑊊', '𑊍'), ('𑊏', '𑊝'), ('𑊟', '𑊩')];

pub const MYANMAR: &'static [(char, char)] = &[
    ('က', '႟'),
    ('ꧠ', 'ꧾ'),
    ('ꩠ', 'ꩿ'),
    ('\u{116d0}', '\u{116e3}'),
];

pub const NABATAEAN: &'static [(char, char)] = &[('𐢀', '𐢞'), ('𐢧', '𐢯')];

pub const NAG_MUNDARI: &'static [(char, char)] = &[('𞓐', '𞓹')];

pub const NANDINAGARI: &'static [(char, char)] =
    &[('𑦠', '𑦧'), ('𑦪', '\u{119d7}'), ('\u{119da}', '𑧤')];

pub const NEW_TAI_LUE: &'static [(char, char)] = &[('ᦀ', 'ᦫ'), ('ᦰ', 'ᧉ'), ('᧐', '᧚'), ('᧞', '᧟')];

pub const NEWA: &'static [(char, char)] = &[('𑐀', '𑑛'), ('𑑝', '𑑡')];

pub const NKO: &'static [(char, char)] = &[('߀', 'ߺ'), ('\u{7fd}', '߿')];

pub const NUSHU: &'static [(char, char)] = &[('𖿡', '𖿡'), ('𛅰', '𛋻')];

pub const NYIAKENG_PUACHUE_HMONG: &'static [(char, char)] =
    &[('𞄀', '𞄬'), ('\u{1e130}', '𞄽'), ('𞅀', '𞅉'), ('𞅎', '𞅏')];

pub const OGHAM: &'static [(char, char)] = &[('\u{1680}', '᚜')];

pub const OL_CHIKI: &'static [(char, char)] = &[('᱐', '᱿')];

pub const OL_ONAL: &'static [(char, char)] =
    &[('\u{1e5d0}', '\u{1e5fa}'), ('\u{1e5ff}', '\u{1e5ff}')];

pub const OLD_HUNGARIAN: &'static [(char, char)] = &[('𐲀', '𐲲'), ('𐳀', '𐳲'), ('𐳺', '𐳿')];

pub const OLD_ITALIC: &'static [(char, char)] = &[('𐌀', '𐌣'), ('𐌭', '𐌯')];

pub const OLD_NORTH_ARABIAN: &'static [(char, char)] = &[('𐪀', '𐪟')];

pub const OLD_PERMIC: &'static [(char, char)] = &[('𐍐', '\u{1037a}')];

pub const OLD_PERSIAN: &'static [(char, char)] = &[('𐎠', '𐏃'), ('𐏈', '𐏕')];

pub const OLD_SOGDIAN: &'static [(char, char)] = &[('𐼀', '𐼧')];

pub const OLD_SOUTH_ARABIAN: &'static [(char, char)] = &[('𐩠', '𐩿')];

pub const OLD_TURKIC: &'static [(char, char)] = &[('𐰀', '𐱈')];

pub const OLD_UYGHUR: &'static [(char, char)] = &[('𐽰', '𐾉')];

pub const ORIYA: &'static [(char, char)] = &[
    ('\u{b01}', 'ଃ'),
    ('ଅ', 'ଌ'),
    ('ଏ', 'ଐ'),
    ('ଓ', 'ନ'),
    ('ପ', 'ର'),
    ('ଲ', 'ଳ'),
    ('ଵ', 'ହ'),
    ('\u{b3c}', '\u{b44}'),
    ('େ', 'ୈ'),
    ('ୋ', '\u{b4d}'),
    ('\u{b55}', '\u{b57}'),
    ('ଡ଼', 'ଢ଼'),
    ('ୟ', '\u{b63}'),
    ('୦', '୷'),
];

pub const OSAGE: &'static [(char, char)] = &[('𐒰', '𐓓'), ('𐓘', '𐓻')];

pub const OSMANYA: &'static [(char, char)] = &[('𐒀', '𐒝'), ('𐒠', '𐒩')];

pub const PAHAWH_HMONG: &'static [(char, char)] =
    &[('𖬀', '𖭅'), ('𖭐', '𖭙'), ('𖭛', '𖭡'), ('𖭣', '𖭷'), ('𖭽', '𖮏')];

pub const PALMYRENE: &'static [(char, char)] = &[('𐡠', '𐡿')];

pub const PAU_CIN_HAU: &'static [(char, char)] = &[('𑫀', '𑫸')];

pub const PHAGS_PA: &'static [(char, char)] = &[('ꡀ', '꡷')];

pub const PHOENICIAN: &'static [(char, char)] = &[('𐤀', '𐤛'), ('𐤟', '𐤟')];

pub const PSALTER_PAHLAVI: &'static [(char, char)] = &[('𐮀', '𐮑'), ('𐮙', '𐮜'), ('𐮩', '𐮯')];

pub const REJANG: &'static [(char, char)] = &[('ꤰ', '꥓'), ('꥟', '꥟')];

pub const RUNIC: &'static [(char, char)] = &[('ᚠ', 'ᛪ'), ('ᛮ', 'ᛸ')];

pub const SAMARITAN: &'static [(char, char)] = &[('ࠀ', '\u{82d}'), ('࠰', '࠾')];

pub const SAURASHTRA: &'static [(char, char)] = &[('ꢀ', '\u{a8c5}'), ('꣎', '꣙')];

pub const SHARADA: &'static [(char, char)] = &[('\u{11180}', '𑇟')];

pub const SHAVIAN: &'static [(char, char)] = &[('𐑐', '𐑿')];

pub const SIDDHAM: &'static [(char, char)] = &[('𑖀', '\u{115b5}'), ('𑖸', '\u{115dd}')];

pub const SIGNWRITING: &'static [(char, char)] = &[
    ('𝠀', '𝪋'),
    ('\u{1da9b}', '\u{1da9f}'),
    ('\u{1daa1}', '\u{1daaf}'),
];

pub const SINHALA: &'static [(char, char)] = &[
    ('\u{d81}', 'ඃ'),
    ('අ', 'ඖ'),
    ('ක', 'න'),
    ('ඳ', 'ර'),
    ('ල', 'ල'),
    ('ව', 'ෆ'),
    ('\u{dca}', '\u{dca}'),
    ('\u{dcf}', '\u{dd4}'),
    ('\u{dd6}', '\u{dd6}'),
    ('ෘ', '\u{ddf}'),
    ('෦', '෯'),
    ('ෲ', '෴'),
    ('𑇡', '𑇴'),
];

pub const SOGDIAN: &'static [(char, char)] = &[('𐼰', '𐽙')];

pub const SORA_SOMPENG: &'static [(char, char)] = &[('𑃐', '𑃨'), ('𑃰', '𑃹')];

pub const SOYOMBO: &'static [(char, char)] = &[('𑩐', '𑪢')];

pub const SUNDANESE: &'static [(char, char)] = &[('\u{1b80}', 'ᮿ'), ('᳀', '᳇')];

pub const SUNUWAR: &'static [(char, char)] =
    &[('\u{11bc0}', '\u{11be1}'), ('\u{11bf0}', '\u{11bf9}')];

pub const SYLOTI_NAGRI: &'static [(char, char)] = &[('ꠀ', '\u{a82c}')];

pub const SYRIAC: &'static [(char, char)] =
    &[('܀', '܍'), ('\u{70f}', '\u{74a}'), ('ݍ', 'ݏ'), ('ࡠ', 'ࡪ')];

pub const TAGALOG: &'static [(char, char)] = &[('ᜀ', '᜕'), ('ᜟ', 'ᜟ')];

pub const TAGBANWA: &'static [(char, char)] = &[('ᝠ', 'ᝬ'), ('ᝮ', 'ᝰ'), ('\u{1772}', '\u{1773}')];

pub const TAI_LE: &'static [(char, char)] = &[('ᥐ', 'ᥭ'), ('ᥰ', 'ᥴ')];

pub const TAI_THAM: &'static [(char, char)] = &[
    ('ᨠ', '\u{1a5e}'),
    ('\u{1a60}', '\u{1a7c}'),
    ('\u{1a7f}', '᪉'),
    ('᪐', '᪙'),
    ('᪠', '᪭'),
];

pub const TAI_VIET: &'static [(char, char)] = &[('ꪀ', 'ꫂ'), ('ꫛ', '꫟')];

pub const TAKRI: &'static [(char, char)] = &[('𑚀', '𑚹'), ('𑛀', '𑛉')];

pub const TAMIL: &'static [(char, char)] = &[
    ('\u{b82}', 'ஃ'),
    ('அ', 'ஊ'),
    ('எ', 'ஐ'),
    ('ஒ', 'க'),
    ('ங', 'ச'),
    ('ஜ', 'ஜ'),
    ('ஞ', 'ட'),
    ('ண', 'த'),
    ('ந', 'ப'),
    ('ம', 'ஹ'),
    ('\u{bbe}', 'ூ'),
    ('ெ', 'ை'),
    ('ொ', '\u{bcd}'),
    ('ௐ', 'ௐ'),
    ('\u{bd7}', '\u{bd7}'),
    ('௦', '௺'),
    ('𑿀', '𑿱'),
    ('𑿿', '𑿿'),
];

pub const TANGSA: &'static [(char, char)] = &[('𖩰', '𖪾'), ('𖫀', '𖫉')];

pub const TANGUT: &'static [(char, char)] =
    &[('𖿠', '𖿠'), ('𗀀', '𘟷'), ('𘠀', '𘫿'), ('𘴀', '𘴈')];

pub const TELUGU: &'static [(char, char)] = &[
    ('\u{c00}', 'ఌ'),
    ('ఎ', 'ఐ'),
    ('ఒ', 'న'),
    ('ప', 'హ'),
    ('\u{c3c}', 'ౄ'),
    ('\u{c46}', '\u{c48}'),
    ('\u{c4a}', '\u{c4d}'),
    ('\u{c55}', '\u{c56}'),
    ('ౘ', 'ౚ'),
    ('ౝ', 'ౝ'),
    ('ౠ', '\u{c63}'),
    ('౦', '౯'),
    ('౷', '౿'),
];

pub const THAANA: &'static [(char, char)] = &[('ހ', 'ޱ')];

pub const THAI: &'static [(char, char)] = &[('ก', '\u{e3a}'), ('เ', '๛')];

pub const TIBETAN: &'static [(char, char)] = &[
    ('ༀ', 'ཇ'),
    ('ཉ', 'ཬ'),
    ('\u{f71}', '\u{f97}'),
    ('\u{f99}', '\u{fbc}'),
    ('྾', '࿌'),
    ('࿎', '࿔'),
    ('࿙', '࿚'),
];

pub const TIFINAGH: &'static [(char, char)] = &[('ⴰ', 'ⵧ'), ('ⵯ', '⵰'), ('\u{2d7f}', '\u{2d7f}')];

pub const TIRHUTA: &'static [(char, char)] = &[('𑒀', '𑓇'), ('𑓐', '𑓙')];

pub const TODHRI: &'static [(char, char)] = &[('\u{105c0}', '\u{105f3}')];

pub const TOTO: &'static [(char, char)] = &[('𞊐', '\u{1e2ae}')];

pub const TULU_TIGALARI: &'static [(char, char)] = &[
    ('\u{11380}', '\u{11389}'),
    ('\u{1138b}', '\u{1138b}'),
    ('\u{1138e}', '\u{1138e}'),
    ('\u{11390}', '\u{113b5}'),
    ('\u{113b7}', '\u{113c0}'),
    ('\u{113c2}', '\u{113c2}'),
    ('\u{113c5}', '\u{113c5}'),
    ('\u{113c7}', '\u{113ca}'),
    ('\u{113cc}', '\u{113d5}'),
    ('\u{113d7}', '\u{113d8}'),
    ('\u{113e1}', '\u{113e2}'),
];

pub const UGARITIC: &'static [(char, char)] = &[('𐎀', '𐎝'), ('𐎟', '𐎟')];

pub const VAI: &'static [(char, char)] = &[('ꔀ', 'ꘫ')];

pub const VITHKUQI: &'static [(char, char)] = &[
    ('𐕰', '𐕺'),
    ('𐕼', '𐖊'),
    ('𐖌', '𐖒'),
    ('𐖔', '𐖕'),
    ('𐖗', '𐖡'),
    ('𐖣', '𐖱'),
    ('𐖳', '𐖹'),
    ('𐖻', '𐖼'),
];

pub const WANCHO: &'static [(char, char)] = &[('𞋀', '𞋹'), ('𞋿', '𞋿')];

pub const WARANG_CITI: &'static [(char, char)] = &[('𑢠', '𑣲'), ('𑣿', '𑣿')];

pub const YEZIDI: &'static [(char, char)] = &[('𐺀', '𐺩'), ('\u{10eab}', '𐺭'), ('𐺰', '𐺱')];

pub const YI: &'static [(char, char)] = &[('ꀀ', 'ꒌ'), ('꒐', '꓆')];

pub const ZANABAZAR_SQUARE: &'static [(char, char)] = &[('𑨀', '\u{11a47}')];
